### ISSUE TITLE
navigation skip button screen reader focus

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt-contrib-core#123]
As the `nav__skip-btn` is positioned off screen, this can cause issues with screen reader focus when used in designs which control the scroll, rather than using the standard overflow scrolling. In these designs, the page will scroll to an undesired position when the screen reader focus is applied to this button.

Rather than positioning off screen, and amending the top position on :focus, the same effect can be achieved using opacity instead:
```less
&__skip-btn {
  position: absolute;
  left: 0;
  margin-top: 0;
  top: 0;
  opacity: 0;
  z-index: 100;
  .transition(opacity @duration ease-in-out);

  html:not(.has-accessibility) & {
    .u-display-none;
  }

  &:focus {
    opacity: 1;
  }
}
```
