### ISSUE TITLE
Misplaced MCQ Button

### ISSUE THREAD

**Issue by henrietta-k** [adaptlearning/adapt-contrib-core#525]
### Subject of the issue/enhancement/features
After submitting an answer to a Multiple Choice Question, there is a circle with either a checkmark or a cross. However, this button is placed right in the middle of the "Show correct answer" and "Show feedback" buttons.

### Your environment
* Chrome 123.0
* MacOS

### Steps to reproduce
Open the "Question Components" tutorial page and scroll down to "Multiple Choice Question." Submit an answer to a question. 

### Expected behaviour
The checkmark/ cross button should be placed somewhere else on the page (it might not even be needed since the individual bars have their own checkmark/ cross symbol). 

### Actual behaviour
A checkmark/ cross button appears in the middle of two buttons: "Show correct answer" and "Show feedback."

### Screenshots (if you can)
![image](https://github.com/adaptlearning/adapt-contrib-mcq/assets/111554249/71a0daa4-7c4c-492c-ac15-be8f2ff38698)

**Comment by oliverfoster** [comment]
This behaviour is for all questions, it comes from the core not the mcq. 

The indicator icon shows the correctness of the answer for the entire question. 

The ticks next to each option in the mcq show only the option correctness at either the user's answer or the correct answer. 

It is possible to hide any of these icons with a small amount of CSS if you find them unsightly or not in keeping with your design.

If you'd like to redesign the core question correctness indicator icon, you will need to consider all of the question components not just the mcq and propose a redesign with a stronger argument.

Question components: mcq, gmcq, text input, slider, matching etc

**Comment by swashbuck** [comment]
We usually hide the marking button with something like:

```less
// Remove marking icon from buttons
.btn__response-container {
  gap: @btn-margin;
}

.btn__marking {
  display: none;
}

.btn__action:not(.is-full-width) {
  margin-inline-end: 0;
}

.btn__feedback:not(.is-full-width) {
  margin-inline-start: 0;
}

.btn__action:not(.is-full-width),
.btn__feedback:not(.is-full-width) {
  width: calc(50% - (@btn-margin / 2));
}
```

You can also read more about marking and correctness on the wiki at:

https://github.com/adaptlearning/adapt_framework/wiki/States-and-indicators

Closing as inactive.
