### ISSUE TITLE
aria-label class not properly hidden

### ISSUE THREAD

**Issue by hanshillen** [adaptlearning/adapt-contrib-core#606]
### Subject of the issue/enhancement/features

The `.aria-label` class is supposed to visually hide content while keeping it available to screen readers. But under certain conditions, that content is still:

1. Selectable, and visible when selected.
2. Blocking mouse clicks.

This seems to be specifically occurring on Windows, for example in Chrome. The issue is made worse if the user has set a minimum font-size in their browser settings, as that makes the hidden text bigger and more likely to have a negative effect.

### Your environment

* 5.41.12
* Windows, Chrome (doesn't occur on MacOS)

### Steps to reproduce

- Create a new course with `adapt create` and open it in Chrome on Windows
- Optionally, increase Chrome's minimum font size through Settings > Appearance > Customize fonts > Minimum Font size 
- Go to the 'Question Components' page
- Select all page content with mouse or <kbd>Ctrl + a</kbd>

### Expected behaviour

The visually hidden text should not be visible at any point 

### Actual behaviour

Visually hidden text is visble

### Screenshots (if you can)

The screenshot below shows a question component with all text content selected. This makes the following aria-label text visible:

* Completion status ("completed", `.js-a11y-completion-description`)
* Component type ("Multiple choice question")
* Feedback live region text, ("You answered incorrectly", `.js-btn-marking-label`). Since this text is positioned on top of the "show markings" button, it makes that part of the button unclickable with a mouse.

![](https://github.com/user-attachments/assets/d868d3e4-c635-411c-8459-773dd9e308fe)

### Notes

It might be easiest replacing the current aria-label class:

https://github.com/adaptlearning/adapt-contrib-core/blob/89a0421ba06e127bfb0b5825a2bd7e839e06d49b/less/core/accessibility.less#L9-L25

with something more inline with other frameworks, such as [bootstrap's visually-hidden](https://github.com/twbs/bootstrap/blob/cbbb567b637e24882fd0fad62bca49e248afb9a4/scss/mixins/_visually-hidden.scss#L9-L16):

```css
.aria-label{
  display: block;
  width: 1px !important;
  height: 1px !important;
  padding: 0 !important;
  margin: -1px !important;
  overflow: hidden !important;
  clip: rect(0, 0, 0, 0) !important;
  white-space: nowrap !important;
  border: 0 !important;
}
```

This is a commonly used and well tested approach for visually hiding content, and the results of many years of the accessibility community trying out different approaches. It does not have the reported side effect.
